title: Spartan-Demo
description: Xilinx Spartan 7 FPGA Programming Demo
theme: minima

basurl: "/spartan-demo"

header_pages:
  - index.md

minima:
  skin: classic

markdown: kramdown
plugins:
  - jekyll-seo-tag

exclude:
  - README.md
  - .gitginore
