title: Spartan-Demo
description: Xilinx Spartan 7 FPGA Programming Demo

baseurl: "/spartan-demo"

remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

markdown: kramdown

just_the_docs:
  color_scheme: light
  search_enabled: true
